version: 2.1

jobs:
  build_compute:
    docker:
      - image: rust
    steps:
      - checkout
      - run:
          command: cargo build
          working_directory: compute/
      - run:
          command: mv compute/target/debug/libcompute.so compute/target/debug/compute.so
      - store_artifacts:
          path: compute/target/debug/compute.so
          destination: compute

workflows:
  my_workflow:
    jobs:
      - build_compute
