version: 2.1

jobs:
  job_1:
    docker:
      - image: ubuntu
    steps:
      - run: sleep 10 && echo 1
  job_2:
    docker:
      - image: ubuntu
    steps:
      - run: sleep 10 && echo 2
  job_3:
    docker:
      - image: ubuntu
    steps:
      - run: sleep 10 && echo 3

workflows:
  my_workflow:
    jobs:
      - job_1
      - job_2:
          requires: ["job_1"]
          type: approval
      - job_3:
          requires: ["job_2"]
