version: 2.1

jobs:
  my_job:
    docker:
      - image: ubuntu
    steps:
      - run: echo Hello World > test.txt
      - store_artifacts:
          path: test.txt
          destination: test

workflows:
  my_workflow:
    jobs:
      - my_job
