version: 2.1

jobs:
  job_1:
    docker:
      - image: ubuntu
    steps:
      - run: echo 1
  job_2:
    docker:
      - image: ubuntu
    steps:
      - run: echo 2
  job_3:
    docker:
      - image: ubuntu
    steps:
      - run: echo 3

workflows:
  my_workflow:
    jobs:
      - job_1
      - job_2
      - job_3
