version: 2.1

jobs:
  my_job:
    docker:
      - image: ubuntu
    steps:
      - run: echo $MY_ENV_VAR

workflows:
  my_workflow:
    jobs:
      - my_job:
          context:
            - my-context
