version: 2.1

jobs:
  job_1:
    docker:
      - image: ubuntu
    steps:
      - run: echo Hello World > test.txt
  job_2:
    docker:
      - image: ubuntu
    steps:
      - run: cat test.txt

workflows:
  my_workflow:
    jobs:
      - job_1
      - job_2:
          requires:
            - job_1
