name: test
run-name: ${{ github.actor }} is trying GitHub Actions
on: [push]
jobs:
  build-compute:
    name: Build compute
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build
        working-directory: compute/
      - uses: actions/upload-artifact@v3
        with:
          name: compute.so
          path: compute/target/debug/libcompute.so
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: |
          bun install
          bun build --minify --outfile=dist/bundle.js index.tsx
          cp public/* dist/
        working-directory: frontend/
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: frontend/dist
  build-server:
    name: Build server
    needs: [build-compute, build-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: server/lib/frontend
      - uses: actions/download-artifact@v3
        with:
          name: compute.so
          path: server/lib/compute
      - run: sudo apt-get update && apt-get install -y tree && tree server/lib
      - uses: snok/install-poetry@v1
      - run: |
          poetry install
          poetry build -f wheel
        working-directory: server
      - uses: actions/upload-artifact@v3
        with:
          name: server
          path: server/dist/*.whl
