name: test
run-name: ${{ github.actor }} is trying GitHub Actions
on: [push]
jobs:
  build-compute:
    name: Build compute
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build && sudo apt-get update && sudo apt-get install -y tree && tree
        working-directory: compute/
      - uses: actions/upload-artifact@v3
        with:
          name: compute.so
          path: compute/target/debug/libcompute.dylib
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: |
          bun install
          bun build --minify --outfile=dist/bundle.js index.tsx
          cp public/* dist/
        working-directory: frontend/
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: frontend/dist
